allowBuilds:
  '@parcel/watcher': true
  es5-ext: true

overrides:
  serialize-javascript: ^7.0.5
  brace-expansion: ^5.0.9
  js-yaml: ^4.3.2
  immutable: ^5.1.8
  mocha>diff: ^9.0.0
  undici: ^7.29.0
  svgo: ^4.1.0
  fast-uri: ^3.1.6
  qs: ^6.16.0
  postcss-selector-parser: ^7.1.3
