name: code_projects Type Check

on:
  push:
    paths:
      - 'frontend/python/rst_code_example_pipeline/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/python/rst_code_example_pipeline/**'

jobs:
  pyright:

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pyright
      run: pip install pyright
    - name: Install rst_code_example_pipeline
      run: pip install -e frontend/python/rst_code_example_pipeline
    - name: Run pyright on rst_code_example_pipeline
      working-directory: frontend/python/rst_code_example_pipeline
      run: pyright .
