name: code_projects Type Check

on:
  push:
    paths:
      - 'frontend/py_modules/code_projects/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/py_modules/code_projects/**'

jobs:
  pyright:

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pyright
      run: pip install pyright
    - name: Run pyright on code_projects
      working-directory: frontend/py_modules/code_projects
      run: pyright .
