name: Typescript Test Suite

on:
  push:
    paths:
      - 'frontend/**/*.ts'
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: frontend


jobs:
  typescript-tests:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ['3.11']
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v4
    - name: Enable Corepack
      run: corepack enable
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: 'frontend'
    - name: Install OS Deps
      run: |
        sudo apt-get update && \
        sudo apt-get install -y \
        crudini
    - name: Install GNAT FSF
      run: |
        ${GITHUB_WORKSPACE}/.github/workflows/install_toolchain.sh --gnat --gnatprove --gprbuild
    - name: Increase max user watches
      run: |
        echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && \
        sudo sysctl -p
    - name: Install dependencies
      run: yarn --immutable
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_frozen.txt
    - name: Build HTML test pages
      run: make site-testing
    - name: Run Typescript tests
      run: yarn run cover
