name: Typescript Test Suite

on:
  push:
    paths:
      - 'frontend/**/*.ts'
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: frontend


jobs:
  typescript-tests:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ['3.10']
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install GNAT FSF
      run: |
        sudo wget -O gnat.tar.gz https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-12.1.0-2/gnat-x86_64-linux-12.1.0-2.tar.gz && \
        sudo tar xzf gnat.tar.gz && \
        sudo mv gnat-* /usr/local/gnat
        sudo echo "/usr/local/gnat/bin" >> $GITHUB_PATH
        sudo wget -O gnatprove.tar.gz https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-12.1.0-1/gnatprove-x86_64-linux-12.1.0-1.tar.gz && \
        sudo tar xzf gnatprove.tar.gz && \
        sudo mv gnatprove-* /usr/local/gnatprove
        sudo echo "/usr/local/gnatprove/bin" >> $GITHUB_PATH
        sudo wget -O gprbuild.tar.gz https://github.com/alire-project/GNAT-FSF-builds/releases/download/gprbuild-22.0.0-1/gprbuild-x86_64-linux-22.0.0-1.tar.gz && \
        sudo tar xzf gprbuild.tar.gz && \
        sudo mv gprbuild-* /usr/local/gprbuild
        sudo echo "/usr/local/gprbuild/bin" >> $GITHUB_PATH
        sudo rm *.tar.gz
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build HTML test pages
      run: make site-testing
    - name: Run Typescript tests
      run: yarn run cover
